apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: subnamespace-admin
rules:
- apiGroups: ["hnc.x-k8s.io"]
  resources: ["namespaces", "subnamespaceanchors"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: subnamespace-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: subnamespace-admin
subjects:
- kind: ServiceAccount
  name: default
